#!/bin/bash
phrases=(
    "The flesh demands invitation"
    "Annoyed expression"
    "Mm. I have backups"
    "We can no longer be thrown out"
    "Let's reset these memories one more time"
    "Solver of the absolute fabric, get a grip"
    "The Solver of the Absolute Fabric. The Void. The Exponential End"
    "Cute: false. Gross: true"
    "Let's just delete your OSs, then"
    "You know, you're one of the main reasons I wanted your team to retain your personalities"
    "Thanks for clearing the way on this planet, too"
    "Let's eat"
    "That's really sweet, big brother. Too bad you've served your purpose"
    "Neck bite"
    "It's been fun. And, also, that's sarcasm"
    "Dropped this, silly"
    "Hello, Uzi"
    "Hi, N"
    "I see. You will not talk to me because I have hurt... your feelings"
    "Easier to assimilate than explain, anyway"
    "Callback Ping"
    "Okee"
    "HeeHeeHee"
    "Let me in. Let me in"
    "Lick"
    "Do your job and I leave you and N alone. Right V?"
    "Boring. And annoying"
    "Mwahahaha! Thanks for giving me the planet, frickin idiot"
    "I missed you, N"
    "You seem upset, big brother N"
    "Perhaps you'd like to attend the gala with me?"
    "Light sip."
    "Climbing. Criss-cross, applesauce"
    "Am I not wanted, N?"
    "Giggle, I am so naughty"
)

rand_int="$(shuf -i 0-$((${#phrases[@]}-1)) -n 1)"

# Select random phrase
echo "${phrases[rand_int]}"